# Generated by Django 4.1.5 on 2023-04-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='accommodation',
            new_name='accommodation_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='food',
            new_name='food_id',
        ),
    ]
