# Generated by Django 4.1.5 on 2023-04-04 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_accommodation_cart_accommodation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='accommodation_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='food_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='accommodation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.accommodation'),
        ),
        migrations.AddField(
            model_name='cart',
            name='food_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.food'),
        ),
    ]
