# Generated by Django 4.1.5 on 2023-04-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_user_user_customuser_name_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='accommodations',
            field=models.ManyToManyField(to='home.accommodation'),
        ),
        migrations.AddField(
            model_name='package',
            name='foods',
            field=models.ManyToManyField(to='home.food'),
        ),
    ]
