# Generated by Django 4.1.5 on 2023-04-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_cart_accommodation_id_remove_cart_food_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='accommodation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='food_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
