# Generated by Django 4.1.5 on 2023-04-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_cart_accommodation_id_alter_cart_food_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.package')),
            ],
        ),
    ]
