# Generated by Django 4.1.5 on 2023-04-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_order_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='home.cartitem'),
        ),
        migrations.AddField(
            model_name='cart',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
